### ISSUE TITLE
Draw Images Swap

### ISSUE THREAD

**Issue by brunotrevisan** [hamarb123/hamarb123.SharpGLES#1]
Hello, how are you? I need to render images, I receive the following parameters from an external dll

ReadOnlySpan data, int width, int height, int pitch

with this information i need to create an image and render it on the screen at 60fps, i'm currently using win2d and canvasAnimateControl but there is no hardware acceleration which has been causing a lot of crashes, is there a possibility to do this with your project? if so how could i create the image with this information i get?

**Comment by hamarb123** [comment]
Hey, sorry I didn't see your issue.
Here's how you'd do that I think:
- Get the raw bytes for the image (have to do this separately)
- Set up a shader for the image (can use 1 for all images)
- Load the image into Open GLES 2.0 the standard way (includes `GLES20.TexImage2D`)
- Draw the image the standard Open GLES 2.0 way

If you don't know how to do the Open GL ES 2.0 steps, any tutorial online would do.
